Update to Java 17, BeanMapper 3.1.2
42BV/beanmapper-spring pull request #45
Opened 2022-09-12 11:52 UTC by marcus-talbot42

2022-09-12 11:54 UTC, marcus-talbot42 commented
Build cannot pass, due to the fact that BeanMapper 3.1.2 hasn't been released to Maven yet.

2022-09-12 13:11 UTC, benjaminparkinson42 commented on src/test/java/io/beanmapper/spring/web/mockmvc/ReturnPassedArgument.java
> +public class ReturnPassedArgument<T extends Persistable> /* implements Delegate<T> */ {
comment /* implements Delegate<T> */

2022-09-12 13:11 UTC, benjaminparkinson42 commented on src/test/java/io/beanmapper/spring/web/mockmvc/ReturnPassedArgument.java
> +//            Deencapsulation.setField(persistable, "id", 42L);
Staat hier ook nog een comment

2022-09-13 13:25 UTC, marcus-talbot42 commented on pom.xml
> +        <el.impl.version>2.2.1-b05</el.impl.version>
Helaas is dat de meest recente versie van een stale project

2022-09-15 09:47 UTC, benjaminparkinson42 commented on src/main/java/io/beanmapper/spring/util/JsonUtil.java
> -            String propertyName = StringUtils.isEmpty(base) ? fieldName : base + "." + fieldName;
![image](https://user-images.githubusercontent.com/105443742/190372017-09503f2c-edac-44ce-b9f9-b0717ffd3c6e.png)
IsEmpty doet al een nullcheck

2022-09-15 09:47 UTC, benjaminparkinson42 commented on src/main/java/io/beanmapper/spring/web/MergedFormMethodArgumentResolver.java
> +        if (mergeId == null || mergeId.isEmpty()) {
![image](https://user-images.githubusercontent.com/105443742/190372286-fb8476e3-bebb-4f08-b001-86c5bf83acd9.png)
IsEmpty doet al een nullcheck

2022-09-15 09:48 UTC, botenbreuk commented on src/main/java/io/beanmapper/spring/util/JsonUtil.java
> +            String propertyName = base == null || base.isEmpty() ? fieldName : base + "." + fieldName;
StringUtils van commons lang3 doet ook de null check
![image](https://user-images.githubusercontent.com/7441477/190372967-88f76fe0-8fdc-4961-a01d-78c7bfe0a424.png)

2022-09-15 10:59 UTC, benjaminparkinson42 approved these changes

2022-09-15 10:59 UTC, benjaminparkinson42 commented on pom.xml
> +            <version>3.12.0</version>
version property

2022-09-15 11:00 UTC, benjaminparkinson42 requested changes

2022-09-15 11:00 UTC, benjaminparkinson42 commented on pom.xml
> +            <version>3.12.0</version>
Version property toevoegen

2022-09-15 11:09 UTC, merged